INSERT INTO transfer (first_name, last_name, 
email_address, address1, address2, city, state, zip)
VALUES
    ('John', 'Doe', 'john.doe@example.com', '123 Main 
St', NULL, 'Anytown', 'CA', '12345'),
('William', 'Perez', 'william.perez@example.com', 
'12345 Oakwood Dr', NULL, 'Anytown', 'CA', '12345'),
('Isabella', 'Rodriguez', 
'isabella.rodriguez@example.com', '56789 Redwood Blvd', 
NULL, 'Anytown', 'CA', '12345'),
('Matthew', 'Martinez', 'matthew.martinez@example.com', 
'90123 Elmwood Ave', NULL, 'Anytown', 'CA', '12345'),
('Abigail', 'Hernandez', 
'abigail.hernandez@example.com', '34567 Oakwood Dr', 
NULL, 'Anytown', 'CA', '12345'),
('Ethan', 'Lopez', 'ethan.lopez@example.com', '78901 
Redwood Ave', NULL, 'Anytown', 'CA', '12345'),
('Sofia', 'Gonzalez', 'sofia.gonzalez@example.com', 
'12345 Oakwood Dr', NULL, 'Anytown', 'CA', '12345'),
('Alexander', 'Perez', 'alexander.perez@example.com', 
'56789 Redwood Blvd', NULL, 'Anytown', 'CA', '12345'),
('Mia', 'Rodriguez', 'mia.rodriguez@example.com', 
'90123 Elmwood Ave', NULL, 'Anytown', 'CA', '12345'),
('Daniel', 'Martinez', 'daniel.martinez@example.com', 
'34567 Oakwood Dr', NULL, 'Anytown', 'CA', '12345'),
('Olivia', 'Hernandez', 'olivia.hernandez@example.com', 
'78901 Redwood Ave', NULL, 'Anytown', 'CA', '12345'),
('James', 'Lopez', 'james.lopez@example.com', '12345 
Oakwood Dr', NULL, 'Anytown', 'CA', '12345'),
('Sophia', 'Gonzalez', 'sophia.gonzalez@example.com', 
'56789 Redwood Blvd', NULL, 'Anytown', 'CA', '12345'),
('William', 'Perez', 'william.perez@example.com', 
'90123 Elmwood Ave', NULL, 'Anytown', 'CA', '12345'),
('Isabella', 'Rodriguez', 
'isabella.rodriguez@example.com', '34567 Oakwood Dr', 
NULL, 'Anytown', 'CA', '12345'),
('Matthew', 'Martinez', 'matthew.martinez@example.com', 
'78901 Redwood Ave', NULL, 'Anytown', 'CA', '12345'),
('Abigail', 'Hernandez', 
'abigail.hernandez@example.com', '12345 Oakwood Dr', 
NULL, 'Anytown', 'CA', '12345'),
('Ethan', 'Lopez', 'ethan.lopez@example.com', '56789 
Redwood Blvd', NULL, 'Anytown', 'CA', '12345'),
('Sofia', 'Gonzalez', 'sofia.gonzalez@example.com', 
'90123 Elmwood Ave', NULL, 'Anytown', 'CA', '12345'),
('Alexander', 'Perez', 'alexander.perez@example.com', 
'34567 Oakwood Dr', NULL, 'Anytown', 'CA', '12345'),
('Mia', 'Rodriguez', 'mia.rodriguez@example.com', 
'78901 Redwood Ave', NULL, 'Anytown', 'CA', '12345'),
('William', 'Perez', 'william.perez@example.com', 
'12345 Oakwood Dr', NULL, 'Anytown', 'CA', '12345'),
('Isabella', 'Rodriguez', 
'isabella.rodriguez@example.com', '56789 Redwood Blvd', 
NULL, 'Anytown', 'CA', '12345'),
('Matthew', 'Martinez', 'matthew.martinez@example.com', 
'90123 Elmwood Ave', NULL, 'Anytown', 'CA', '12345'),
('Abigail', 'Hernandez', 
'abigail.hernandez@example.com', '34567 Oakwood Dr', 
NULL, 'Anytown', 'CA', '12345'),
('Ethan', 'Lopez', 'ethan.lopez@example.com', '78901 
Redwood Ave', NULL, 'Anytown', 'CA', '12345'),
('Sofia', 'Gonzalez', 'sofia.gonzalez@example.com', 
'12345 Oakwood Dr', NULL, 'Anytown', 'CA', '12345'),
('Alexander', 'Perez', 'alexander.perez@example.com', 
'56789 Redwood Blvd', NULL, 'Anytown', 'CA', '12345'),
('Mia', 'Rodriguez', 'mia.rodriguez@example.com', 
'90123 Elmwood Ave', NULL, 'Anytown', 'CA', '12345'),
('Daniel', 'Martinez', 'daniel.martinez@example.com', 
'34567 Oakwood Dr', NULL, 'Anytown', 'CA', '12345'),
('Olivia', 'Hernandez', 'olivia.hernandez@example.com', 
'78901 Redwood Ave', NULL, 'Anytown', 'CA', '12345'),
('James', 'Lopez', 'james.lopez@example.com', '12345 
Oakwood Dr', NULL, 'Anytown', 'CA', '12345'),
('Sophia', 'Gonzalez', 'sophia.gonzalez@example.com', 
'56789 Redwood Blvd', NULL, 'Anytown', 'CA', '12345'),
('William', 'Perez', 'william.perez@example.com', 
'90123 Elmwood Ave', NULL, 'Anytown', 'CA', '12345'),
('Isabella', 'Rodriguez', 
'isabella.rodriguez@example.com', '34567 Oakwood Dr', 
NULL, 'Anytown', 'CA', '12345'),
('Matthew', 'Martinez', 'matthew.martinez@example.com', 
'78901 Redwood Ave', NULL, 'Anytown', 'CA', '12345'),
('Abigail', 'Hernandez', 
'abigail.hernandez@example.com', '12345 Oakwood Dr', 
NULL, 'Anytown', 'CA', '12345'),
('Ethan', 'Lopez', 'ethan.lopez@example.com', '56789 
Redwood Blvd', NULL, 'Anytown', 'CA', '12345'),
('Sofia', 'Gonzalez', 'sofia.gonzalez@example.com', 
'90123 Elmwood Ave', NULL, 'Anytown', 'CA', '12345'),
('Alexander', 'Perez', 'alexander.perez@example.com', 
'34567 Oakwood Dr', NULL, 'Anytown', 'CA', '12345'),
('Mia', 'Rodriguez', 'mia.rodriguez@example.com', 
'78901 Redwood Ave', NULL, 'Anytown', 'CA', '12345'),
('William', 'Perez', 'william.perez@example.com', 
'12345 Oakwood Dr', NULL, 'Anytown', 'CA', '12345'),
('Isabella', 'Rodriguez', 
'isabella.rodriguez@example.com', '56789 Redwood Blvd', 
NULL, 'Anytown', 'CA', '12345'),
('Matthew', 'Martinez', 'matthew.martinez@example.com', 
'90123 Elmwood Ave', NULL, 'Anytown', 'CA', '12345'),
('Abigail', 'Hernandez', 
'abigail.hernandez@example.com', '34567 Oakwood Dr', 
NULL, 'Anytown', 'CA', '12345')